import sqlite3
a = sqlite3.connect('chinnu..db')
b = a.cursor()
b.execute("CREATE TABLE CRICKET(TEAM_N0 NUMBER,TEAM_NAME VARCHAR ,TEAM_CAPTAIN VARCHAR, TEAM_COACH VARCHAR, SCORE NUMBER)")
b.execute("INSERT INTO CRICKET VALUES (1, 'CHETHU STRIKERS', 'CHETHU', 'RAGHAVENDRA', 420)")

b.execute("INSERT INTO CRICKET VALUES (2, 'BLACKBULLS', 'GNANA', 'FATHIMA', 360)")

b.execute("INSERT INTO CRICKET VALUES (3, 'SURYA', 'CHANDRA', 'NAKSHATRA', 143)")

b.execute("INSERT INTO CRICKET VALUES (4, 'BHAGYALAKSHMI', 'BHAGYA', 'ABHIRAM', 250)")

b.execute("INSERT INTO CRICKET VALUES (5, 'INTERCEPTOR', 'AKASH', 'MOHITH', 300)")

a.commit()

c = b.execute("SELECT * FROM CRICKET")
print(list(c))
